version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/packages/reishi"
      - "/packages/enoki"
      - "/packages/oyster"
      - "/packages/physarum"
      - "/lab"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
